name: Bulk Import Issues
on:
  workflow_dispatch:
    # Allows you to trigger it manually

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Import Issues
      uses: github/marketplace/actions/issue-importer-action@v1 # Verify latest version
      with:
        file-path: './tasks.csv'
        file-format: 'csv'
        github-token: ${{ secrets.GITHUB_TOKEN }}
